spring:
  application:
    name: seat_reservation

  datasource:
    url: jdbc:postgresql://localhost:5432/seat_reservation
    username: reservation_user
    password: reservation_password

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

app:
  jwt:
    secret: "change-this-local-secret-to-at-least-32-characters-long"

server:
  port: 8082

  
